#prefix used by the plugin when sending chat messages.
chat-prefix: "Aspen-Prefix"

#prefix used if the player has no prefix permissions.
default-prefix: '&6[&r{#812409}Spectator&6]&r'

#Use $prefix to place the prefix in your format.
prefix-format: '&6[&r$prefix&6]&r'

#prefixes available for players.
#you can use the AspenPrefix.prefix.<prefixName> permission node to grant prefixes.
Prefixes:
  Staff: "{#FF8317}Staff"
  Moderator: "{#00c2ff}Mod"
  VIP: "{#9f29ff}VIP"
  Guest: "{#11806a}Player"
